# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright 2025-2026 AKKODIS.
# SPDX-FileContributor: Romain Baville

from domain.assignment.base import AssignmentProblem
from domain.assignment.constraints.constraints_config import ConstraintsConfig
from domain.assignment.constraints.quantities_constraints import QuantitiesConstraints
from domain.assignment.score.matching_config import MatchingConfig
from domain.assignment.score.matching_reward_functions import RewardFunctions
from domain.assignment.score.score_config import ScoreConfig
from domain.objective import Objective

problem_00_prompt: str = (
    "I work for a company that manage R&D projects. For each project, we need to affect people based on their skills "
    "level and the skills required by the project. The ip.csv file contains the skill mastered by employees (on a "
    "scale from 1 to 5). The project.csv file contains the amount of people required for each project and for each "
    "skills. I would like to match people to projects based on their skills. An employee can be assigned to only one "
    "project at a time. Can you help me find a way to make this affectaction procedure as efficient as possible ?"
)  # This problem is not in the IndustryOR.json file but the one use to built this project

# Problem
left_labels: tuple[ str, ...] = (
    "PierreDupont",
    "MarieLemoine",
    "JeanMartin",
    "ClaireBernard",
    "SophieDubois",
    "AlainLefevre",
    "IsabelleMoreau",
    "LucPetit",
    "CamilleLeroy",
    "NicolasLefevre",
    "AliceRobert",
    "LaurentDufresne",
    "NathalieGautier",
    "GérardPires",
    "CatherineLeclerc",
    "FrançoisRichard",
    "JulieBoucher",
    "ThomasLefranc",
    "PaulineMorin",
    "DavidGauthier",
    "SandraLefevre",
    "MichelTanguy",
    "ÉliseGuérin",
    "HugoPerrier",
    "LaurenceLemoine",
    "AntoineHenry",
    "CarolineRoussel",
    "CharlesDubois",
    "EmilieMarchand"
)
right_labels: tuple[ str, ...] = (
    "NovaTech",
    "ZenithX",
    "HorizonLabs",
    "QuantumEdge",
    "SkyBridgeSolutions",
    "QuantumHorizon",
    "VelocityHub",
    "TerraNovaLabs",
    "NextGenInnovations",
    "SynergyX"
)

# Score
labels: tuple[
    str,
    ...] = ( "React", "SQL", "Python", "Docker", "Vue.js", "Kubernetes", "JavaScript", "Django", "Node.js", "Git" )
left_vals: dict[ tuple[ str, str ], float ] = {
    ( "PierreDupont", "React" ): 5.,
    ( "PierreDupont", "SQL" ): 0.,
    ( "PierreDupont", "Python" ): 0.,
    ( "PierreDupont", "Docker" ): 0.,
    ( "PierreDupont", "Vue.js" ): 5.,
    ( "PierreDupont", "Kubernetes" ): 0.,
    ( "PierreDupont", "JavaScript" ): 4.,
    ( "PierreDupont", "Django" ): 0.,
    ( "PierreDupont", "Node.js" ): 1.,
    ( "PierreDupont", "Git" ): 0.,
    ( "MarieLemoine", "React" ): 3.,
    ( "MarieLemoine", "SQL" ): 2.,
    ( "MarieLemoine", "Python" ): 0.,
    ( "MarieLemoine", "Docker" ): 0.,
    ( "MarieLemoine", "Vue.js" ): 2.,
    ( "MarieLemoine", "Kubernetes" ): 0.,
    ( "MarieLemoine", "JavaScript" ): 5.,
    ( "MarieLemoine", "Django" ): 0.,
    ( "MarieLemoine", "Node.js" ): 3.,
    ( "MarieLemoine", "Git" ): 1.,
    ( "JeanMartin", "React" ): 0.,
    ( "JeanMartin", "SQL" ): 4.,
    ( "JeanMartin", "Python" ): 2.,
    ( "JeanMartin", "Docker" ): 4.,
    ( "JeanMartin", "Vue.js" ): 0.,
    ( "JeanMartin", "Kubernetes" ): 3.,
    ( "JeanMartin", "JavaScript" ): 0.,
    ( "JeanMartin", "Django" ): 5.,
    ( "JeanMartin", "Node.js" ): 0.,
    ( "JeanMartin", "Git" ): 1.,
    ( "ClaireBernard", "React" ): 3.,
    ( "ClaireBernard", "SQL" ): 0.,
    ( "ClaireBernard", "Python" ): 0.,
    ( "ClaireBernard", "Docker" ): 0.,
    ( "ClaireBernard", "Vue.js" ): 3.,
    ( "ClaireBernard", "Kubernetes" ): 0.,
    ( "ClaireBernard", "JavaScript" ): 3.,
    ( "ClaireBernard", "Django" ): 0.,
    ( "ClaireBernard", "Node.js" ): 4.,
    ( "ClaireBernard", "Git" ): 1.,
    ( "SophieDubois", "React" ): 0.,
    ( "SophieDubois", "SQL" ): 2.,
    ( "SophieDubois", "Python" ): 3.,
    ( "SophieDubois", "Docker" ): 1.,
    ( "SophieDubois", "Vue.js" ): 0.,
    ( "SophieDubois", "Kubernetes" ): 4.,
    ( "SophieDubois", "JavaScript" ): 0.,
    ( "SophieDubois", "Django" ): 4.,
    ( "SophieDubois", "Node.js" ): 0.,
    ( "SophieDubois", "Git" ): 3.,
    ( "AlainLefevre", "React" ): 3.,
    ( "AlainLefevre", "SQL" ): 0.,
    ( "AlainLefevre", "Python" ): 0.,
    ( "AlainLefevre", "Docker" ): 2.,
    ( "AlainLefevre", "Vue.js" ): 4.,
    ( "AlainLefevre", "Kubernetes" ): 1.,
    ( "AlainLefevre", "JavaScript" ): 4.,
    ( "AlainLefevre", "Django" ): 0.,
    ( "AlainLefevre", "Node.js" ): 5.,
    ( "AlainLefevre", "Git" ): 4.,
    ( "IsabelleMoreau", "React" ): 0.,
    ( "IsabelleMoreau", "SQL" ): 1.,
    ( "IsabelleMoreau", "Python" ): 0.,
    ( "IsabelleMoreau", "Docker" ): 5.,
    ( "IsabelleMoreau", "Vue.js" ): 4.,
    ( "IsabelleMoreau", "Kubernetes" ): 0.,
    ( "IsabelleMoreau", "JavaScript" ): 0.,
    ( "IsabelleMoreau", "Django" ): 1.,
    ( "IsabelleMoreau", "Node.js" ): 2.,
    ( "IsabelleMoreau", "Git" ): 3.,
    ( "LucPetit", "React" ): 1.,
    ( "LucPetit", "SQL" ): 1.,
    ( "LucPetit", "Python" ): 3.,
    ( "LucPetit", "Docker" ): 1.,
    ( "LucPetit", "Vue.js" ): 4.,
    ( "LucPetit", "Kubernetes" ): 0.,
    ( "LucPetit", "JavaScript" ): 3.,
    ( "LucPetit", "Django" ): 2.,
    ( "LucPetit", "Node.js" ): 2.,
    ( "LucPetit", "Git" ): 5.,
    ( "CamilleLeroy", "React" ): 1.,
    ( "CamilleLeroy", "SQL" ): 2.,
    ( "CamilleLeroy", "Python" ): 0.,
    ( "CamilleLeroy", "Docker" ): 2.,
    ( "CamilleLeroy", "Vue.js" ): 5.,
    ( "CamilleLeroy", "Kubernetes" ): 4.,
    ( "CamilleLeroy", "JavaScript" ): 0.,
    ( "CamilleLeroy", "Django" ): 5.,
    ( "CamilleLeroy", "Node.js" ): 0.,
    ( "CamilleLeroy", "Git" ): 4.,
    ( "NicolasLefevre", "React" ): 1.,
    ( "NicolasLefevre", "SQL" ): 5.,
    ( "NicolasLefevre", "Python" ): 3.,
    ( "NicolasLefevre", "Docker" ): 0.,
    ( "NicolasLefevre", "Vue.js" ): 1.,
    ( "NicolasLefevre", "Kubernetes" ): 0.,
    ( "NicolasLefevre", "JavaScript" ): 1.,
    ( "NicolasLefevre", "Django" ): 5.,
    ( "NicolasLefevre", "Node.js" ): 0.,
    ( "NicolasLefevre", "Git" ): 5.,
    ( "AliceRobert", "React" ): 5.,
    ( "AliceRobert", "SQL" ): 4.,
    ( "AliceRobert", "Python" ): 0.,
    ( "AliceRobert", "Docker" ): 5.,
    ( "AliceRobert", "Vue.js" ): 3.,
    ( "AliceRobert", "Kubernetes" ): 3.,
    ( "AliceRobert", "JavaScript" ): 3.,
    ( "AliceRobert", "Django" ): 0.,
    ( "AliceRobert", "Node.js" ): 2.,
    ( "AliceRobert", "Git" ): 4.,
    ( "LaurentDufresne", "React" ): 0.,
    ( "LaurentDufresne", "SQL" ): 0.,
    ( "LaurentDufresne", "Python" ): 5.,
    ( "LaurentDufresne", "Docker" ): 1.,
    ( "LaurentDufresne", "Vue.js" ): 0.,
    ( "LaurentDufresne", "Kubernetes" ): 4.,
    ( "LaurentDufresne", "JavaScript" ): 0.,
    ( "LaurentDufresne", "Django" ): 4.,
    ( "LaurentDufresne", "Node.js" ): 0.,
    ( "LaurentDufresne", "Git" ): 0.,
    ( "NathalieGautier", "React" ): 5.,
    ( "NathalieGautier", "SQL" ): 1.,
    ( "NathalieGautier", "Python" ): 3.,
    ( "NathalieGautier", "Docker" ): 2.,
    ( "NathalieGautier", "Vue.js" ): 3.,
    ( "NathalieGautier", "Kubernetes" ): 5.,
    ( "NathalieGautier", "JavaScript" ): 4.,
    ( "NathalieGautier", "Django" ): 4.,
    ( "NathalieGautier", "Node.js" ): 3.,
    ( "NathalieGautier", "Git" ): 3.,
    ( "GérardPires", "React" ): 1.,
    ( "GérardPires", "SQL" ): 0.,
    ( "GérardPires", "Python" ): 4.,
    ( "GérardPires", "Docker" ): 0.,
    ( "GérardPires", "Vue.js" ): 3.,
    ( "GérardPires", "Kubernetes" ): 5.,
    ( "GérardPires", "JavaScript" ): 0.,
    ( "GérardPires", "Django" ): 2.,
    ( "GérardPires", "Node.js" ): 1.,
    ( "GérardPires", "Git" ): 3.,
    ( "CatherineLeclerc", "React" ): 2.,
    ( "CatherineLeclerc", "SQL" ): 4.,
    ( "CatherineLeclerc", "Python" ): 4.,
    ( "CatherineLeclerc", "Docker" ): 0.,
    ( "CatherineLeclerc", "Vue.js" ): 4.,
    ( "CatherineLeclerc", "Kubernetes" ): 2.,
    ( "CatherineLeclerc", "JavaScript" ): 5.,
    ( "CatherineLeclerc", "Django" ): 5.,
    ( "CatherineLeclerc", "Node.js" ): 4.,
    ( "CatherineLeclerc", "Git" ): 2.,
    ( "FrançoisRichard", "React" ): 1.,
    ( "FrançoisRichard", "SQL" ): 2.,
    ( "FrançoisRichard", "Python" ): 1.,
    ( "FrançoisRichard", "Docker" ): 3.,
    ( "FrançoisRichard", "Vue.js" ): 4.,
    ( "FrançoisRichard", "Kubernetes" ): 2.,
    ( "FrançoisRichard", "JavaScript" ): 0.,
    ( "FrançoisRichard", "Django" ): 3.,
    ( "FrançoisRichard", "Node.js" ): 5.,
    ( "FrançoisRichard", "Git" ): 0.,
    ( "JulieBoucher", "React" ): 5.,
    ( "JulieBoucher", "SQL" ): 5.,
    ( "JulieBoucher", "Python" ): 5.,
    ( "JulieBoucher", "Docker" ): 5.,
    ( "JulieBoucher", "Vue.js" ): 4.,
    ( "JulieBoucher", "Kubernetes" ): 0.,
    ( "JulieBoucher", "JavaScript" ): 0.,
    ( "JulieBoucher", "Django" ): 5.,
    ( "JulieBoucher", "Node.js" ): 1.,
    ( "JulieBoucher", "Git" ): 0.,
    ( "ThomasLefranc", "React" ): 4.,
    ( "ThomasLefranc", "SQL" ): 5.,
    ( "ThomasLefranc", "Python" ): 5.,
    ( "ThomasLefranc", "Docker" ): 1.,
    ( "ThomasLefranc", "Vue.js" ): 0.,
    ( "ThomasLefranc", "Kubernetes" ): 1.,
    ( "ThomasLefranc", "JavaScript" ): 2.,
    ( "ThomasLefranc", "Django" ): 0.,
    ( "ThomasLefranc", "Node.js" ): 0.,
    ( "ThomasLefranc", "Git" ): 4.,
    ( "PaulineMorin", "React" ): 1.,
    ( "PaulineMorin", "SQL" ): 0.,
    ( "PaulineMorin", "Python" ): 0.,
    ( "PaulineMorin", "Docker" ): 1.,
    ( "PaulineMorin", "Vue.js" ): 3.,
    ( "PaulineMorin", "Kubernetes" ): 2.,
    ( "PaulineMorin", "JavaScript" ): 3.,
    ( "PaulineMorin", "Django" ): 1.,
    ( "PaulineMorin", "Node.js" ): 2.,
    ( "PaulineMorin", "Git" ): 4.,
    ( "DavidGauthier", "React" ): 0.,
    ( "DavidGauthier", "SQL" ): 2.,
    ( "DavidGauthier", "Python" ): 0.,
    ( "DavidGauthier", "Docker" ): 2.,
    ( "DavidGauthier", "Vue.js" ): 2.,
    ( "DavidGauthier", "Kubernetes" ): 1.,
    ( "DavidGauthier", "JavaScript" ): 0.,
    ( "DavidGauthier", "Django" ): 0.,
    ( "DavidGauthier", "Node.js" ): 0.,
    ( "DavidGauthier", "Git" ): 5.,
    ( "SandraLefevre", "React" ): 5.,
    ( "SandraLefevre", "SQL" ): 2.,
    ( "SandraLefevre", "Python" ): 1.,
    ( "SandraLefevre", "Docker" ): 5.,
    ( "SandraLefevre", "Vue.js" ): 5.,
    ( "SandraLefevre", "Kubernetes" ): 3.,
    ( "SandraLefevre", "JavaScript" ): 0.,
    ( "SandraLefevre", "Django" ): 4.,
    ( "SandraLefevre", "Node.js" ): 0.,
    ( "SandraLefevre", "Git" ): 3.,
    ( "MichelTanguy", "React" ): 5.,
    ( "MichelTanguy", "SQL" ): 0.,
    ( "MichelTanguy", "Python" ): 1.,
    ( "MichelTanguy", "Docker" ): 3.,
    ( "MichelTanguy", "Vue.js" ): 5.,
    ( "MichelTanguy", "Kubernetes" ): 5.,
    ( "MichelTanguy", "JavaScript" ): 5.,
    ( "MichelTanguy", "Django" ): 1.,
    ( "MichelTanguy", "Node.js" ): 0.,
    ( "MichelTanguy", "Git" ): 3.,
    ( "ÉliseGuérin", "React" ): 0.,
    ( "ÉliseGuérin", "SQL" ): 3.,
    ( "ÉliseGuérin", "Python" ): 5.,
    ( "ÉliseGuérin", "Docker" ): 3.,
    ( "ÉliseGuérin", "Vue.js" ): 2.,
    ( "ÉliseGuérin", "Kubernetes" ): 4.,
    ( "ÉliseGuérin", "JavaScript" ): 1.,
    ( "ÉliseGuérin", "Django" ): 4.,
    ( "ÉliseGuérin", "Node.js" ): 0.,
    ( "ÉliseGuérin", "Git" ): 3.,
    ( "HugoPerrier", "React" ): 0.,
    ( "HugoPerrier", "SQL" ): 3.,
    ( "HugoPerrier", "Python" ): 5.,
    ( "HugoPerrier", "Docker" ): 2.,
    ( "HugoPerrier", "Vue.js" ): 0.,
    ( "HugoPerrier", "Kubernetes" ): 4.,
    ( "HugoPerrier", "JavaScript" ): 0.,
    ( "HugoPerrier", "Django" ): 4.,
    ( "HugoPerrier", "Node.js" ): 0.,
    ( "HugoPerrier", "Git" ): 0.,
    ( "LaurenceLemoine", "React" ): 0.,
    ( "LaurenceLemoine", "SQL" ): 2.,
    ( "LaurenceLemoine", "Python" ): 4.,
    ( "LaurenceLemoine", "Docker" ): 2.,
    ( "LaurenceLemoine", "Vue.js" ): 0.,
    ( "LaurenceLemoine", "Kubernetes" ): 4.,
    ( "LaurenceLemoine", "JavaScript" ): 0.,
    ( "LaurenceLemoine", "Django" ): 3.,
    ( "LaurenceLemoine", "Node.js" ): 0.,
    ( "LaurenceLemoine", "Git" ): 1.,
    ( "AntoineHenry", "React" ): 0.,
    ( "AntoineHenry", "SQL" ): 3.,
    ( "AntoineHenry", "Python" ): 5.,
    ( "AntoineHenry", "Docker" ): 5.,
    ( "AntoineHenry", "Vue.js" ): 0.,
    ( "AntoineHenry", "Kubernetes" ): 2.,
    ( "AntoineHenry", "JavaScript" ): 0.,
    ( "AntoineHenry", "Django" ): 1.,
    ( "AntoineHenry", "Node.js" ): 0.,
    ( "AntoineHenry", "Git" ): 2.,
    ( "CarolineRoussel", "React" ): 3.,
    ( "CarolineRoussel", "SQL" ): 4.,
    ( "CarolineRoussel", "Python" ): 4.,
    ( "CarolineRoussel", "Docker" ): 5.,
    ( "CarolineRoussel", "Vue.js" ): 0.,
    ( "CarolineRoussel", "Kubernetes" ): 5.,
    ( "CarolineRoussel", "JavaScript" ): 3.,
    ( "CarolineRoussel", "Django" ): 3.,
    ( "CarolineRoussel", "Node.js" ): 5.,
    ( "CarolineRoussel", "Git" ): 2.,
    ( "CharlesDubois", "React" ): 5.,
    ( "CharlesDubois", "SQL" ): 3.,
    ( "CharlesDubois", "Python" ): 1.,
    ( "CharlesDubois", "Docker" ): 5.,
    ( "CharlesDubois", "Vue.js" ): 3.,
    ( "CharlesDubois", "Kubernetes" ): 2.,
    ( "CharlesDubois", "JavaScript" ): 0.,
    ( "CharlesDubois", "Django" ): 2.,
    ( "CharlesDubois", "Node.js" ): 2.,
    ( "CharlesDubois", "Git" ): 4.,
    ( "EmilieMarchand", "React" ): 3.,
    ( "EmilieMarchand", "SQL" ): 2.,
    ( "EmilieMarchand", "Python" ): 2.,
    ( "EmilieMarchand", "Docker" ): 2.,
    ( "EmilieMarchand", "Vue.js" ): 3.,
    ( "EmilieMarchand", "Kubernetes" ): 0.,
    ( "EmilieMarchand", "JavaScript" ): 3.,
    ( "EmilieMarchand", "Django" ): 0.,
    ( "EmilieMarchand", "Node.js" ): 0.,
    ( "EmilieMarchand", "Git" ): 0.
}
right_vals: dict[ tuple[ str, str ], float ] = {
    ( "NovaTech", "React" ): 0.,
    ( "NovaTech", "SQL" ): 2.,
    ( "NovaTech", "Python" ): 1.,
    ( "NovaTech", "Docker" ): 1.,
    ( "NovaTech", "Vue.js" ): 2.,
    ( "NovaTech", "Kubernetes" ): 0.,
    ( "NovaTech", "JavaScript" ): 1.,
    ( "NovaTech", "Django" ): 1.,
    ( "NovaTech", "Node.js" ): 1.,
    ( "NovaTech", "Git" ): 1.,
    ( "ZenithX", "React" ): 0.,
    ( "ZenithX", "SQL" ): 1.,
    ( "ZenithX", "Python" ): 1.,
    ( "ZenithX", "Docker" ): 1.,
    ( "ZenithX", "Vue.js" ): 1.,
    ( "ZenithX", "Kubernetes" ): 0.,
    ( "ZenithX", "JavaScript" ): 2.,
    ( "ZenithX", "Django" ): 1.,
    ( "ZenithX", "Node.js" ): 3.,
    ( "ZenithX", "Git" ): 2.,
    ( "HorizonLabs", "React" ): 1.,
    ( "HorizonLabs", "SQL" ): 1.,
    ( "HorizonLabs", "Python" ): 1.,
    ( "HorizonLabs", "Docker" ): 2.,
    ( "HorizonLabs", "Vue.js" ): 1.,
    ( "HorizonLabs", "Kubernetes" ): 3.,
    ( "HorizonLabs", "JavaScript" ): 1.,
    ( "HorizonLabs", "Django" ): 1.,
    ( "HorizonLabs", "Node.js" ): 2.,
    ( "HorizonLabs", "Git" ): 1.,
    ( "QuantumEdge", "React" ): 2.,
    ( "QuantumEdge", "SQL" ): 1.,
    ( "QuantumEdge", "Python" ): 1.,
    ( "QuantumEdge", "Docker" ): 3.,
    ( "QuantumEdge", "Vue.js" ): 0.,
    ( "QuantumEdge", "Kubernetes" ): 2.,
    ( "QuantumEdge", "JavaScript" ): 1.,
    ( "QuantumEdge", "Django" ): 1.,
    ( "QuantumEdge", "Node.js" ): 2.,
    ( "QuantumEdge", "Git" ): 3.,
    ( "SkyBridgeSolutions", "React" ): 0.,
    ( "SkyBridgeSolutions", "SQL" ): 3.,
    ( "SkyBridgeSolutions", "Python" ): 3.,
    ( "SkyBridgeSolutions", "Docker" ): 2.,
    ( "SkyBridgeSolutions", "Vue.js" ): 1.,
    ( "SkyBridgeSolutions", "Kubernetes" ): 1.,
    ( "SkyBridgeSolutions", "JavaScript" ): 2.,
    ( "SkyBridgeSolutions", "Django" ): 2.,
    ( "SkyBridgeSolutions", "Node.js" ): 3.,
    ( "SkyBridgeSolutions", "Git" ): 1.,
    ( "QuantumHorizon", "React" ): 3.,
    ( "QuantumHorizon", "SQL" ): 0.,
    ( "QuantumHorizon", "Python" ): 3.,
    ( "QuantumHorizon", "Docker" ): 1.,
    ( "QuantumHorizon", "Vue.js" ): 0.,
    ( "QuantumHorizon", "Kubernetes" ): 0.,
    ( "QuantumHorizon", "JavaScript" ): 2.,
    ( "QuantumHorizon", "Django" ): 3.,
    ( "QuantumHorizon", "Node.js" ): 0.,
    ( "QuantumHorizon", "Git" ): 2.,
    ( "VelocityHub", "React" ): 4.,
    ( "VelocityHub", "SQL" ): 2.,
    ( "VelocityHub", "Python" ): 0.,
    ( "VelocityHub", "Docker" ): 3.,
    ( "VelocityHub", "Vue.js" ): 2.,
    ( "VelocityHub", "Kubernetes" ): 0.,
    ( "VelocityHub", "JavaScript" ): 3.,
    ( "VelocityHub", "Django" ): 4.,
    ( "VelocityHub", "Node.js" ): 2.,
    ( "VelocityHub", "Git" ): 2.,
    ( "TerraNovaLabs", "React" ): 1.,
    ( "TerraNovaLabs", "SQL" ): 5.,
    ( "TerraNovaLabs", "Python" ): 4.,
    ( "TerraNovaLabs", "Docker" ): 2.,
    ( "TerraNovaLabs", "Vue.js" ): 0.,
    ( "TerraNovaLabs", "Kubernetes" ): 0.,
    ( "TerraNovaLabs", "JavaScript" ): 2.,
    ( "TerraNovaLabs", "Django" ): 5.,
    ( "TerraNovaLabs", "Node.js" ): 3.,
    ( "TerraNovaLabs", "Git" ): 5.,
    ( "NextGenInnovations", "React" ): 4.,
    ( "NextGenInnovations", "SQL" ): 0.,
    ( "NextGenInnovations", "Python" ): 0.,
    ( "NextGenInnovations", "Docker" ): 0.,
    ( "NextGenInnovations", "Vue.js" ): 5.,
    ( "NextGenInnovations", "Kubernetes" ): 2.,
    ( "NextGenInnovations", "JavaScript" ): 4.,
    ( "NextGenInnovations", "Django" ): 5.,
    ( "NextGenInnovations", "Node.js" ): 2.,
    ( "NextGenInnovations", "Git" ): 4.,
    ( "SynergyX", "React" ): 4.,
    ( "SynergyX", "SQL" ): 4.,
    ( "SynergyX", "Python" ): 2.,
    ( "SynergyX", "Docker" ): 1.,
    ( "SynergyX", "Vue.js" ): 1.,
    ( "SynergyX", "Kubernetes" ): 2.,
    ( "SynergyX", "JavaScript" ): 2.,
    ( "SynergyX", "Django" ): 0.,
    ( "SynergyX", "Node.js" ): 0.,
    ( "SynergyX", "Git" ): 4.
}
objective: Objective = Objective.MAXIMIZE
weights: dict[ str, float ] = {
    "React": 1.,
    "SQL": 1.,
    "Python": 1.,
    "Docker": 1.,
    "Vue.js": 1.,
    "Kubernetes": 1.,
    "JavaScript": 1.,
    "Django": 1.,
    "Node.js": 1.,
    "Git": 1.
}
reward_function: RewardFunctions = RewardFunctions.MIN

matching_config: MatchingConfig = MatchingConfig(
    labels=labels,
    left_vals=left_vals,
    right_vals=right_vals,
    objective=objective,
    weights=weights,
    reward_function=reward_function
)

score_config: ScoreConfig = ScoreConfig( use_matching=True, matching_config=matching_config )

# Constraints
max_right_entites: dict[ str, float ] = {
    "PierreDupont": 1.,
    "MarieLemoine": 1.,
    "JeanMartin": 1.,
    "ClaireBernard": 1.,
    "SophieDubois": 1.,
    "AlainLefevre": 1.,
    "IsabelleMoreau": 1.,
    "LucPetit": 1.,
    "CamilleLeroy": 1.,
    "NicolasLefevre": 1.,
    "AliceRobert": 1.,
    "LaurentDufresne": 1.,
    "NathalieGautier": 1.,
    "GérardPires": 1.,
    "CatherineLeclerc": 1.,
    "FrançoisRichard": 1.,
    "JulieBoucher": 1.,
    "ThomasLefranc": 1.,
    "PaulineMorin": 1.,
    "DavidGauthier": 1.,
    "SandraLefevre": 1.,
    "MichelTanguy": 1.,
    "ÉliseGuérin": 1.,
    "HugoPerrier": 1.,
    "LaurenceLemoine": 1.,
    "AntoineHenry": 1.,
    "CarolineRoussel": 1.,
    "CharlesDubois": 1.,
    "EmilieMarchand": 1.
}
min_right_entites: dict[ str, float ] = {
    "PierreDupont": 1.,
    "MarieLemoine": 1.,
    "JeanMartin": 1.,
    "ClaireBernard": 1.,
    "SophieDubois": 1.,
    "AlainLefevre": 1.,
    "IsabelleMoreau": 1.,
    "LucPetit": 1.,
    "CamilleLeroy": 1.,
    "NicolasLefevre": 1.,
    "AliceRobert": 1.,
    "LaurentDufresne": 1.,
    "NathalieGautier": 1.,
    "GérardPires": 1.,
    "CatherineLeclerc": 1.,
    "FrançoisRichard": 1.,
    "JulieBoucher": 1.,
    "ThomasLefranc": 1.,
    "PaulineMorin": 1.,
    "DavidGauthier": 1.,
    "SandraLefevre": 1.,
    "MichelTanguy": 1.,
    "ÉliseGuérin": 1.,
    "HugoPerrier": 1.,
    "LaurenceLemoine": 1.,
    "AntoineHenry": 1.,
    "CarolineRoussel": 1.,
    "CharlesDubois": 1.,
    "EmilieMarchand": 1.
}
min_left_entites: dict[ str, float ] = {
    "NovaTech": 1.,
    "ZenithX": 1.,
    "HorizonLabs": 1.,
    "QuantumEdge": 1.,
    "SkyBridgeSolutions": 1.,
    "QuantumHorizon": 1.,
    "VelocityHub": 1.,
    "TerraNovaLabs": 1.,
    "NextGenInnovations": 1.,
    "SynergyX": 1.
}

quantities_constraints: QuantitiesConstraints = QuantitiesConstraints(
    max_right_entities=max_right_entites, min_right_entities=min_right_entites, min_left_entities=min_left_entites
)

constraints_config: ConstraintsConfig = ConstraintsConfig(
    multiple_same_assignment=False, use_quantities_constraints=True, quantities_constraints=quantities_constraints
)

problem_00_domain: AssignmentProblem = AssignmentProblem(
    left_labels=left_labels,
    right_labels=right_labels,
    score_config=score_config,
    constraints_config=constraints_config
)

# TODO: fund a way of testing the resutl despite the multiple solution
